language: ruby
rvm:
  - 2.7.0
services:
  - postgresql
before_script:
  - psql -c "create database backend_test; create role microswansons with createdb login password 'secret_goes_here'; ALTER DATABASE backend_development OWNER TO microswansons;" -U postgres
env:
  - DB_PASS=secret_goes_here
